edition = "2021"

max_width = 80
array_width = 80
attr_fn_like_width = 80
comment_width = 80
chain_width = 80
fn_call_width = 80
single_line_if_else_max_width = 80

format_code_in_doc_comments = true
fn_single_line = true
format_macro_matchers = true
format_strings = true
merge_derives = false
overflow_delimited_expr = true
reorder_modules = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
where_single_line = true
unstable_features = true

imports_granularity = "Module"
group_imports = "StdExternalCrate"
